spring:
  application:
    name: Task_Management_System
  datasource:
    url: jdbc:postgresql://localhost:5432/Task_Management
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.xml
springdoc:
  swagger-ui:
    enabled: true
    path: /api/doc-ui/
  api-docs:
    enabled: true

app:
  server-url: http://localhost:8080
  jwt-secret: ${JWT_SECRET :awdaasoifjaofosfajoasjhddsahsgflshgoiwioeghrweliurhgpwerjghwleiwergjhfyjyfghjgjfiwrehglwejkrglkwerjhglewuirghlweurhgdwad}